CREATE TABLE IF NOT EXISTS articles (
    id SERIAL PRIMARY KEY,
    center_id INT NOT NULL,
    title VARCHAR(255) NOT NULL UNIQUE,
    descr TEXT NOT NULL,
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_center FOREIGN KEY (center_id) REFERENCES centers(id) ON DELETE CASCADE
);
