CREATE TABLE IF NOT EXISTS centers (
    id SERIAL PRIMARY KEY,
    centerName VARCHAR(255) NOT NULL UNIQUE,
    centerPassword VARCHAR(255) NOT NULL,
    centerAddress VARCHAR(255) NOT NULL,
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
