CREATE TABLE IF NOT EXISTS patients (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `fullName` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255)    NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `center_id` INT UNSIGNED NOT NULL,
    `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY(id),
    UNIQUE KEY(email),
    FOREIGN KEY (`center_id`) REFERENCES centers(`id`) ON DELETE CASCADE
);
