CREATE TABLE IF NOT EXISTS centers (
    id SERIAL PRIMARY KEY,
    centerName VARCHAR(255) NOT NULL UNIQUE,
    centerPassword VARCHAR(255) NOT NULL,
    centerEmail VARCHAR(255) NOT NULL UNIQUE,
    centerCity VARCHAR(255) NOT NULL UNIQUE,
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
