CREATE TABLE IF NOT EXISTS patients (
    id SERIAL PRIMARY KEY,
    fullName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone    VARCHAR(255) NOT NULL,
    date     VARCHAR(255) NOT NULL,
    id_number VARCHAR(255) NOT NULL,
    center_id INT NOT NULL,
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    first_login BOOL  NOT NULL DEFAULT true
    CONSTRAINT fk_center FOREIGN KEY (center_id) REFERENCES centers(id) ON DELETE CASCADE
);
